name: 京东签到

on:
  workflow_dispatch:
  schedule:
     - cron: '1 7,16 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/tutuh001/ioinndaec2341.git ~/ioinndaec2341
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/ioinndaec2341
          npm install
      - name: '运行 【京东签到】'
        if: env.JD_COOKIE
        run: |
          cd ~/ioinndaec2341
          node jd_bean_sign.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
       
