name: 京东种豆得豆

on:
  workflow_dispatch:
  schedule:
     - cron: '0 1-13/2,23 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/tutuh001/jd_action.git ~/jd_action
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/jd_action
          npm install
      - name: '运行 【京东种豆得豆】'
        if: env.JD_COOKIE
        run: |
          cd ~/jd_action
          node jd_plantBean.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
